{
    "openapi": "3.0.0",
    "info": {
      "title": "Trailers App API Documentation",
      "description": "In this documentation you will be able to consult the API end-points and also test all available routes. Do not forget to register and carry out the authorization.",
      "contact": {
        "email": "devpbdias@gmail.com"
      },
      "version": "1.0.0"
    },
    "servers": [
      {
        "url": "http://localhost:3004",
        "description": "Local Server"
      },
      {
        "url": "https://app-trailer-movies.onrender.com/",
        "description": "Web Server"
      }
    ],
    "paths": {
      "/user/": {
        "post": {
          "summary": "Create a new user",
          "description": "Route responsible for creating a new user",
          "tags": ["Users"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Users": {
                    "value": {
                      "name": "Paulo Bruno",
                      "userName": "devpbdias",
                      "email": "devpbdias@gmail.com",
                      "password": "basket123",
                      "avatar": "https://imgur.com/Lae9CiB"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "201": {
              "description": "Created",
              "content": {
                "application/json": {
                  "schemma": {
                    "type": "object",
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      },
      "/user": {
        "get": {
          "summary": "Search all users",
          "description": "Route responsible for fetching all users",
          "tags": ["Users"],
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/User"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/user/{id}/": {
        "get": {
          "summary": "Search user by id",
          "description": "Route responsible for searching for user by id",
          "tags": ["Users"],
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "type": "string",
              "description": "User ID",
              "required": true
            }
          ],
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      },
      "/user/{id}": {
        "patch": {
          "summary": "Update user by id",
          "description": "Route responsible for editing the user by id",
          "tags": ["Users"],
          "security": [{ "bearerAuth": [] }],
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "type": "string",
              "description": "User ID",
              "required": true
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "Users": {
                    "value": {
                      "name": "Paulo Dias"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "401": {
              "description": "Unauthorized"
            },
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object",
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          }
        }
      },
      "/login": {
        "post": {
          "summary": "Login to Trailers App",
          "description": "Route responsible for logging in a registered user",
          "tags": ["Login"],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                },
                "examples": {
                  "User": {
                    "value": {
                      "email": "devpbdias@gmail.com",
                      "password": "basket123"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK"
            }
          }
        }
      },
      "/movie/": {
        "post": {
          "summary": "Create a new Movies",
          "description": "Route responsible for creating a new Movies",
          "tags": ["Movies"],
          "security": [{ "bearerAuth": [] }],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Movies"
                },
                "examples": {
                  "Movies": {
                    "value": {
                        "name": "Avengers",
                        "year": "2020",
                        "actors": "RDJ, Chris Evans, Tom Hidleston",
                        "director": "Russo Brothers",
                        "image": "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
                        "platform": "Disney+",
                        "category": "Action",
                        "type": "movie",
                        "company": "Marvel Studios",
                        "linkTrailer": "https://www.youtube.com/watch?v=PgrmbRID0eY&ab_channel=MarvelBrasil"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "401": {
              "description": "Unauthorized"
            },
            "400": {
              "description": "Not Found"
            },
            "201": {
              "description": "Created",
              "content": {
                "application/json": {
                  "schemma": {
                    "type": "object",
                    "$ref": "#/components/schemas/Movies"
                  }
                }
              }
            }
          }
        }
      },
      "/movie": {
        "get": {
          "summary": "Search all movies",
          "description": "Route responsible for fetching all movies",
          "tags": ["Movies"],
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "array",
                    "items": {
                      "$ref": "#/components/schemas/News"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/movie/latest": {
        "get": {
          "summary": "Search latest Movies",
          "description": "Route responsible for fetching latest Movies",
          "tags": ["Movies"],
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schemma": {
                    "type": "object",
                    "$ref": "#/components/schemas/Movies"
                  }
                }
              }
            }
          }
        }
      },
      "/movie/{id}/": {
        "get": {
          "summary": "Search Movies by id",
          "description": "Route responsible for fetching Movies by id",
          "tags": ["Movies"],
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "type": "string",
              "description": "Movies ID",
              "required": true
            }
          ],
          "responses": {
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schemma": {
                    "type": "object",
                    "$ref": "#/components/schemas/Movies"
                  }
                }
              }
            }
          }
        }
      },
      "/movie/{id}": {
        "patch": {
          "summary": "Update a Movie",
          "description": "Route responsible for updating a Movie",
          "tags": ["Movies"],
          "security": [{ "bearerAuth": [] }],
          "parameters": [
            {
              "in": "path",
              "name": "id",
              "type": "string",
              "description": "Movie ID",
              "required": true
            }
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Movies"
                },
                "examples": {
                  "Movie": {
                    "value": {
                        "name": "Avengers",
                        "year": "2020",
                        "actors": "RDJ, Chris Evans, Tom Hidleston",
                        "director": "Russo Brothers",
                        "image": "https://static.wikia.nocookie.net/dublagem/images/d/d0/Marvels-avengers-boxart-02-ps4-04feb20-en-us.jpg/revision/latest/scale-to-width-down/350?cb=20201023012810&path-prefix=pt-br",
                        "platform": "Disney+",
                        "category": "Action",
                        "type": "movie",
                        "company": "Marvel Studios",
                        "linkTrailer": "https://www.youtube.com/watch?v=PgrmbRID0eY&ab_channel=MarvelBrasil"
                    }
                  }
                }
              }
            }
          },
          "responses": {
            "401": {
              "description": "Unauthorized"
            },
            "400": {
              "description": "Not Found"
            },
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schemma": {
                    "type": "object",
                    "$ref": "#/components/schemas/News"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "securitySchemes": {
        "bearerAuth": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
        }
      },
      "schemas": {
        "User": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "userName": {
              "type": "string"
            },
            "email": {
              "type": "string"
            },
            "password": {
              "type": "string"
            },
            "avatar": {
              "type": "string"
            }
          }
        },
        "Movies": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "year": {
              "type": "string"
            },
            "director": {
              "type": "string"
            },
            "actors": {
              "type": "string"
            },
            "image": {
              "type": "string"
            },
            "platform": {
              "type": "string"
            },
            "category": {
              "type": "string"
            },
            "type": {
                "type": "string"
            },
            "company": {
                "type": "string"
            },
            "linkTrailer": {
                "type": "string"
            },
            "createdAt": {
                "type": "date"
            }
          }
        }
      }
    }
  }